//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid Booking_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> Student_ID { get; set; }
        public Nullable<System.Guid> Counsellor_ID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Counsellor Counsellor { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
