//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counsellor
    {
        public Counsellor()
        {
            this.Bookings = new HashSet<Booking>();
            this.Comments = new HashSet<Comment>();
            this.Counsellor_Rating = new HashSet<Counsellor_Rating>();
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public System.Guid Counsellor_ID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email_ID { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public string Introduction { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Counsellor_Rating> Counsellor_Rating { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
