//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion_Question
    {
        public Discussion_Question()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Question_ID { get; set; }
        public string Statement { get; set; }
        public string Title { get; set; }
        public Nullable<double> Rating_Stars { get; set; }
        public Nullable<System.Guid> Category_ID { get; set; }
        public Nullable<System.Guid> Student_ID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Student Student { get; set; }
    }
}
