//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_University
    {
        public int Program_Uni_ID { get; set; }
        public Nullable<int> Program_ID { get; set; }
        public Nullable<int> University_ID { get; set; }
        public Nullable<int> Fee_ID { get; set; }
        public string Admission_Criteria { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
        public Nullable<int> Duration { get; set; }
        public string HSSC_Criteria { get; set; }
        public string SSC_Criteria { get; set; }
        public string Reference { get; set; }
    
        public virtual Fee_Structure Fee_Structure { get; set; }
        public virtual Program Program { get; set; }
        public virtual University University { get; set; }
    }
}
