//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Academic_Credentials = new HashSet<Academic_Credentials>();
            this.Answers = new HashSet<Answer>();
            this.Bookings = new HashSet<Booking>();
            this.Bookings1 = new HashSet<Booking>();
            this.Comments = new HashSet<Comment>();
            this.Counsellor_Rating = new HashSet<Counsellor_Rating>();
            this.Discussion_Question = new HashSet<Discussion_Question>();
            this.Qualifications = new HashSet<Qualification>();
            this.Results = new HashSet<Result>();
        }
    
        public System.Guid Student_ID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email_ID { get; set; }
        public string Picture { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
    
        public virtual ICollection<Academic_Credentials> Academic_Credentials { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Booking> Bookings1 { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Counsellor_Rating> Counsellor_Rating { get; set; }
        public virtual ICollection<Discussion_Question> Discussion_Question { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
