//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public University()
        {
            this.Program_University = new HashSet<Program_University>();
        }
    
        public System.Guid University_ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Introduction { get; set; }
        public string Admission_Details { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> CurrentApplicationId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ImageSize { get; set; }
    
        public virtual ICollection<Program_University> Program_University { get; set; }
    }
}
